// <auto-generated />
using System;
using DotnetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetAPI.Migrations
{
    [DbContext(typeof(YuzzContext))]
    [Migration("20251115164232_CreatedAuditLogTable")]
    partial class CreatedAuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DotnetAPI.Models.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_user_name");

                    b.ToTable("APP-USER");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Changes")
                        .HasColumnType("TEXT")
                        .HasColumnName("changes");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("log_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Battery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BessId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BESS_id");

                    b.Property<int>("CurrentCharging")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_charging");

                    b.Property<int>("CurrentMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_max");

                    b.Property<int>("ModbusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("modbus_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PwrMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pwr_max");

                    b.Property<int>("SocMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soc_max");

                    b.Property<int>("SocMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soc_min");

                    b.Property<int>("VoltageAbsorption")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_absorption");

                    b.Property<int>("VoltageMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_max");

                    b.Property<int>("VoltageMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_min");

                    b.HasKey("Id")
                        .HasName("pk_battery");

                    b.HasIndex("BessId")
                        .HasDatabaseName("ix_battery_bess_id");

                    b.HasIndex("ModbusId")
                        .IsUnique()
                        .HasDatabaseName("ix_battery_modbus_id");

                    b.ToTable("BATTERY");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Bess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CurrentMaxAcIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_max_ac_in");

                    b.Property<int>("CurrentMaxAcOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_max_ac_out");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OperationModeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OPERATION_MODE_id");

                    b.Property<int>("ThresholdCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threshold_current");

                    b.HasKey("Id")
                        .HasName("pk_bess");

                    b.HasIndex("OperationModeId")
                        .HasDatabaseName("ix_bess_operation_mode_id");

                    b.ToTable("BESS");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.OperationMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_operation_modes");

                    b.ToTable("operation_modes", (string)null);
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Pcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BatteryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BATTERY_id");

                    b.Property<int>("CanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_id");

                    b.Property<int>("PcsModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PCS_MODEL_id");

                    b.HasKey("Id")
                        .HasName("pk_pcs");

                    b.HasIndex("BatteryId")
                        .HasDatabaseName("ix_pcs_battery_id");

                    b.HasIndex("CanId")
                        .IsUnique()
                        .HasDatabaseName("ix_pcs_can_id");

                    b.HasIndex("PcsModelId")
                        .HasDatabaseName("ix_pcs_pcs_model_id");

                    b.ToTable("PCS");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.PcsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CurrentMaxDc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_max_dc");

                    b.Property<int>("ModbusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("modbus_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RatedPower")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rated_power");

                    b.Property<int>("VoltageMaxDc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_max_dc");

                    b.Property<int>("VoltageMinDc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_min_dc");

                    b.HasKey("Id")
                        .HasName("pk_pcs_model");

                    b.ToTable("PCS_MODEL");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Battery", b =>
                {
                    b.HasOne("DotnetAPI.Models.Domain.Bess", "Bess")
                        .WithMany()
                        .HasForeignKey("BessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BESS_BATTERY");

                    b.Navigation("Bess");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Bess", b =>
                {
                    b.HasOne("DotnetAPI.Models.Domain.OperationMode", "OperationMode")
                        .WithMany()
                        .HasForeignKey("OperationModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("OPERATION_MODE_BESS");

                    b.Navigation("OperationMode");
                });

            modelBuilder.Entity("DotnetAPI.Models.Domain.Pcs", b =>
                {
                    b.HasOne("DotnetAPI.Models.Domain.Battery", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BATTERY_PCS");

                    b.HasOne("DotnetAPI.Models.Domain.PcsModel", "PcsModel")
                        .WithMany()
                        .HasForeignKey("PcsModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PCS_MODEL");

                    b.Navigation("Battery");

                    b.Navigation("PcsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
